# Generated by Django 3.2.14 on 2022-07-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1850-05-06'),
            preserve_default=False,
        ),
    ]
